services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WebEtDesign\RgpdBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Exporter,Tests,Kernel.php}'

  WebEtDesign\RgpdBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  WebEtDesign\RgpdBundle\Command\RgpdReminderOldPasswordCommand:
    arguments:
      - ~
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'
      - '@router'
      - '%wd_rgpd.old_password_reminder%'
